[package]
name = "crawfish"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/Ludi-1/chrust/"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
